### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by splincode** [ameerthehacker/express-icode#1]
![image](https://user-images.githubusercontent.com/12021443/37993870-8a40deb8-3218-11e8-8626-acf908dacf7c.png)

**Comment by ameerthehacker** [comment]
This is because I have hosted the express server in an ec2 instance without an ssl certificate thus you need to allow insecure access from chrome. Try to login with username: **ameerthehacker**, password: **new** then this small icon will appear at the top of your chrome window 

![capture](https://user-images.githubusercontent.com/15448192/38042087-01177d68-32d1-11e8-9bb2-2f7d9c6d8e9f.PNG)

Click on **Load unsafe script** and then the screen will reload. Now try to login again and it should work
